parameters:
    oro_note.form.type.note.class:                 Oro\Bundle\NoteBundle\Form\Type\NoteType
    oro_note.form.type.note_api.class:             Oro\Bundle\NoteBundle\Form\Type\NoteApiType
    oro_note.form.handler.note.class:              Oro\Bundle\NoteBundle\Form\Handler\NoteHandler
    oro_note.form.handler.note_api.class:          Oro\Bundle\NoteBundle\Form\Handler\NoteApiHandler

services:
    oro_note.form.type.note:
        class: %oro_note.form.type.note.class%
        tags:
            - { name: form.type, alias: oro_note }

    oro_note.form.type.note_api:
        class: %oro_note.form.type.note_api.class%
        arguments:
            - '@oro_entity_config.config_manager'
        tags:
            - { name: form.type, alias: oro_note_api }

    oro_note.form.note:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'oro_note_form'
            - 'oro_note'

    oro_note.form.note.api:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - ~
            - 'oro_note_api'

    oro_note.form.handler.note:
        class: %oro_note.form.handler.note.class%
        arguments:
            - '@oro_note.form.note'
            - '@request_stack'
            - '@doctrine'
            - '@oro_activity.manager'

    oro_note.form.handler.note_api:
        class: %oro_note.form.handler.note_api.class%
        arguments:
            - '@oro_note.form.note.api'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity_config.config_manager'
